name: semaia_state
description: "State and business logic"
version: 0.2.0
homepage: "https://github.com/kit-g/semaia.git"
repository: "https://github.com/kit-g/semaia.git"
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  firebase_auth: 6.0.0
  flutter:
    sdk: flutter
  google_sign_in: ^7.1.1
  ksuid: 1.0.0
  logging: 1.3.0
  provider: ^6.1.5
  semaia_models:
    path: '../models'
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:

