name: semaia
description: "A query tool"
publish_to: none
homepage: "https://github.com/kit-g/semaia.git"
repository: "https://github.com/kit-g/semaia.git"
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  animated_tree_view: ^2.3.0
  csv: ^6.0.0
  file_saver: ^0.3.1
  firebase_core: ^4.0.0
  google_sign_in_web: 1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_code_editor:
    git: https://github.com/kingsway-technologies/flutter-code-editor.git
  flutter_highlight: ^0.7.0
  flutter_markdown: ^0.7.7+1
  flutter_svg: 2.2.0
  flutter_web_plugins:
    sdk: flutter
  go_router: 16.0.0
  highlight: ^0.7.0
  logging: ^1.3.0
  multi_split_view: ^3.5.0
  network_utils:
    git:
      url: "https://github.com/kit-g/dart-network-utils"
      ref: "ef0116cd9db159a2a28cc68d5c4ae6c5ddca5611"
  number_paginator: ^0.4.1
  package_info_plus: ^8.3.0
  pluto_grid: ^8.0.0
  provider: ^6.1.5
  semaia_api:
    path: 'shared/api'
  semaia_language:
    path: 'shared/language'
  semaia_models:
    path: 'shared/models'
  semaia_state:
    path: 'shared/state'
  shared_preferences: ^2.5.3
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/favicon/
    - assets/svg/ # https://www.svgrepo.com/svg/306591/postgresql
  fonts:
    - family: "Lato"
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 200

    - family: "Mono"
      fonts:
        - asset: assets/fonts/Mono/JetBrainsMono-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/Mono/JetBrainsMono-VariableFont_wght.ttf
          weight: 400

    - family: "Parisienne"
      fonts:
        - asset: assets/fonts/Parisienne/Parisienne-Regular.ttf

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/favicon/favicon.png"
    theme_color: "#5f5ff6"
  macos:
    generate: true
    image_path: "assets/favicon/favicon.png"

dependency_overrides:
  intl: 0.20.2
  dio: ^5.8.0+1
  dio_web_adapter: ^2.1.1
