name: semaia_models
description: "Various data models"
version: 0.1.0
homepage: "https://github.com/kit-g/semaia.git"
repository: "https://github.com/kit-g/semaia.git"

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.19.0
