name: semaia_language
description: "Language resources"
version: 0.0.1
homepage: ""

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:

