name: semaia_api
description: "Wrapper around API"
version: 0.2.0
homepage: "https://github.com/kit-g/semaia.git"
repository: "https://github.com/kit-g/semaia.git"
publish_to: none

environment:
  sdk: "^3.8.1"

dependencies:
  semaia_models:
    path: "../models"
  http: 1.4.0
  dart_http_sse: ^1.0.3
  logging: 1.3.0
  crypto: 3.0.6
  network_utils:
    git:
      url: "https://github.com/kit-g/dart-network-utils"
      ref: "ef0116cd9db159a2a28cc68d5c4ae6c5ddca5611"

dev_dependencies:
  flutter_lints: ^6.0.0
